const express = require('express');
const router = express.Router();
const controller = require('./controllers/controller.js');
const userController = require('./controllers/userController.js');
const requireLogin = require('./middleware/requireLogin');
const requireAdmin = require('./middleware/requireAdmin');
router.post('/checkUser', userController.checkUser);
router.post('/addUser', userController.addUser);
router.post('/addTask', requireLogin, controller.addTask);
router.get('/getTasks', requireLogin, controller.getTasks);
router.get('/getNumberOfTasks', requireLogin, controller.getNumOfTasks);
router.put('/removeTask', requireLogin, controller.removeTask);
router.get('/getUsers', requireLogin, requireAdmin, controller.getUsers);
router.get('/getNumberOfUsers',requireLogin,requireAdmin,controller.getNumOfUsers);
router.get('/getNumOfFinTasks',requireLogin,controller.getNumOfFinTasks);
router.get('/getFinishedTasks',requireLogin,controller.getFinishedTasks);
module.exports = router;